/*
 * Copyright (c) 2026 Renato Mauro
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <string.h>
#include <zephyr/kernel.h>
#include <zephyr/device.h>

#include <zephyr/toolchain.h>
#include <zephyr/drivers/clock_control.h>

#include "mock_common.h"
#include "mock_stm32_clock_control.h"

static struct device_state mock_device_state = {
	.init_res = 0, /* 0 in Zephyr means successfully initialized */
	.initialized = true,
};

static int mock_clock_on(const struct device *dev, clock_control_subsys_t sys)
{
	UNUSED(dev);
	UNUSED(sys);
	return 0; /* Ritorna successo */
}

static int mock_clock_off(const struct device *dev, clock_control_subsys_t sys)
{
	UNUSED(dev);
	UNUSED(sys);
	return 0;
}

/* The clock api mock struct must be positioned in the right section. */
STRUCT_SECTION_ITERABLE(clock_control_driver_api, mock_clock_api) = {
	.on = mock_clock_on,
	.off = mock_clock_off,
};

/* Resolution of __device_dts_ord_20:
 * The driver searches for a 'struct device' generated by DeviceTree.
 * Create a static mock in RAM named as requested by the linker.
 */
const struct device __device_dts_ord_20 = {
	.name = "mock_stm32_clock_control",
	.api = &mock_clock_api,
	.state = &mock_device_state,
};
